# Generated by Django 6.0.5 on 2026-05-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gato.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'Gato',
                'verbose_name_plural': 'Gatos',
                'indexes': [models.Index(fields=['nombre'], name='gato_gato_nombre_b1e7a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'nombre'), name='categoria_nombre')],
            },
        ),
    ]
